name: Java CI with Gradle

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: master 브랜치로 이동
      uses: actions/checkout@v3
      with:
        ref: production
    
    - name: JDK 17 설치
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
    
    - name: make application-prod.properties
      run: |
        cd ./src/main/resources
        touch ./application-prod.properties
        echo "${{ secrets.ENV_PROD }}" > ./application-prod.properties
      working-directory: ./server
    
    - name: gradlew에 실행 권한 부여
      run: chmod +x ./gradlew
      working-directory: ./server
    
    - name: 프로젝트 빌드
      run: ./gradlew clean build -x test
      working-directory: ./server
